### ISSUE TITLE
怎么失败了？啥也没显示

### ISSUE THREAD

**Issue by briteming** [chansee97/nuxt-blog-v2#2]
https://issue-nuxt-blog-owrk.vercel.app/

按你的readme操作的。
fork了你这个仓库：https://github.com/briteming/issue-nuxt-blog
issues repo: https://github.com/briteming/inb-issues

怎么解决？谢谢回复！
------------------------

**Comment by chansee97** [comment]
https://github.com/chansee97/issue-nuxt-blog#%E4%BF%AE%E6%94%B9%E4%B8%AA%E4%BA%BA%E4%BB%8B%E7%BB%8D

https://github.com/briteming/briteming 这个仓库你有吗？

**Comment by briteming** [comment]
hi。

访问https://issue-nuxt-blog-owrk.vercel.app/ ，显示：
Could not fetch data from https://api.github.com/repos/briteming/briteming/readme

我的issues repo的地址怎么变成了briteming/briteming？
我明明把issues repo的地址设置为了inb-issues

**Comment by briteming** [comment]
我设置了VITE_BLOGS_REPO的值为inb-issues

**Comment by briteming** [comment]
hi.

我新建了https://github.com/briteming/briteming 这个仓库，不过访问https://issue-nuxt-blog-vjst.vercel.app/ ，怎么不显示帖子呢？我在这里https://github.com/briteming/inb-issues/issues/1 发了一个issue,但是https://issue-nuxt-blog-vjst.vercel.app/ 怎么不显示这个帖子呢？

**Comment by chansee97** [comment]
![2024-12-04_09-34-59](https://github.com/user-attachments/assets/ee1406da-9a6e-44f7-987e-7e4aeaaefcfa)

VITE_BLOGS_REPO确认没有问题重新部署

**Comment by briteming** [comment]
确认VITE_BLOGS_REPO没有问题,其值为inb-issues，我写的是inb-issues，对吗？但是https://issue-nuxt-blog-ab71.vercel.app/ 一样的不显示帖子，真是奇怪。
谢谢回复！

**Comment by chansee97** [comment]
所有和仓库有关系的变量都没有读到，配置有问题

**Comment by chansee97** [comment]
![2024-12-04_10-21-32](https://github.com/user-attachments/assets/86d5bb95-bf73-42b4-8e01-caf9c961bb49)
![2024-12-04_10-21-45](https://github.com/user-attachments/assets/97db8442-70df-4202-b391-5f028602aeb0)

**Comment by ymbrite** [comment]
hi.

 我重新用另一个github用户名fork了你的项目：https://github.com/ymbrite/issue-nuxt-blog
也建立了issues repo: https://github.com/ymbrite/inb-issues
自我介绍页面：https://github.com/ymbrite/ymbrite/

然后新注册了一个vercel账号。按照你的readme操作，得到的结果：https://issue-nuxt-blog-xvl8.vercel.app/
难道是因为github token的问题？我看你只勾选了public_repo,我勾选了整个repo. 勾选整个repo,包括了public_repo，这应该没有问题吧？

**Comment by ymbrite** [comment]
你在environment variables那里的三项是怎么填的?
可以写出来吗？（可以隐去github token的值）

**Comment by ymbrite** [comment]
我觉得问题就出在environment variables这里。要确保正确

**Comment by chansee97** [comment]
![2024-12-05_13-46-26](https://github.com/user-attachments/assets/34e97bf6-47b9-47fe-b109-f1c764be0910)

**Comment by ymbrite** [comment]
hi.

按你的参数顺序搞了，得到https://issue-nuxt-blog-ec3m.vercel.app/ ，依旧不显示帖子https://github.com/ymbrite/inb-issues/issues/1 ，算了，不折腾了

**Comment by ymbrite** [comment]
hi.

你可否新建一个issues repo, 再部署一遍，这次不绑定域名，然后把vercel显示的你的网站的地址发出来？
谢谢你！

**Comment by chansee97** [comment]
验证过了，github的接口验证政策可能变了，现在部署项目必须有VITE_GITHUB_TOKEN
你的博客已经可以正常显示了 https://issue-nuxt-blog-cyan.vercel.app/

**Comment by chansee97** [comment]
默认分类必须是Blog，注意大小写

**Comment by ymbrite** [comment]
默认分类是Blog,我改blog为Blog了。
https://issue-nuxt-blog-vthm.vercel.app/blog/Blog还是不显示帖子
